[link1]
edges = ["H1", "S1"]
dataRate = "1Gbps"
delay = "0ms"

[link2]
edges = ["H2", "S1"]
dataRate = "1Gbps"
delay = "0ms"

[link3]
edges = ["H3", "S1"]
dataRate = "1Gbps"
delay = "0ms"

[link4]
edges = ["H4", "S1"]
dataRate = "1Gbps"
delay = "0ms"

[link5]
edges = ["H5", "S9"]
dataRate = "1Gbps"
delay = "0ms"

[link6]
edges = ["H6", "S9"]
dataRate = "1Gbps"
delay = "0ms"

[link7]
edges = ["H7", "S9"]
dataRate = "1Gbps"
delay = "0ms"

[link8]
edges = ["H8", "S9"]
dataRate = "1Gbps"
delay = "0ms"

[link9]
edges = ["H9", "S5"]
dataRate = "1Gbps"
delay = "0ms"

[link10]
edges = ["H10", "S5"]
dataRate = "1Gbps"
delay = "0ms"

[link11]
edges = ["H11", "S5"]
dataRate = "1Gbps"
delay = "0ms"

[link12]
edges = ["H12", "S5"]
dataRate = "1Gbps"
delay = "0ms"

[link13]
edges = ["H13", "S7"]
dataRate = "1Gbps"
delay = "0ms"

[link14]
edges = ["H14", "S7"]
dataRate = "1Gbps"
delay = "0ms"

[link15]
edges = ["H15", "S7"]
dataRate = "1Gbps"
delay = "0ms"

[link16]
edges = ["H16", "S7"]
dataRate = "1Gbps"
delay = "0ms"

[link17]
edges = ["S1", "S2"]
dataRate = "1Gbps"
delay = "0ms"

[link18]
edges = ["S1", "S3"]
dataRate = "1Gbps"
delay = "0ms"

[link19]
edges = ["S1", "S4"]
dataRate = "1Gbps"
delay = "0ms"

[link20]
edges = ["S2", "S5"]
dataRate = "1Gbps"
delay = "0ms"

[link21]
edges = ["S2", "S6"]
dataRate = "1Gbps"
delay = "0ms"

[link22]
edges = ["S3", "S5"]
dataRate = "1Gbps"
delay = "0ms"

[link23]
edges = ["S3", "S6"]
dataRate = "1Gbps"
delay = "0ms"

[link24]
edges = ["S4", "S6"]
dataRate = "1Gbps"
delay = "0ms"

[link25]
edges = ["S4", "S7"]
dataRate = "1Gbps"
delay = "0ms"

[link26]
edges = ["S5", "S9"]
dataRate = "1Gbps"
delay = "0ms"

[link27]
edges = ["S6", "S9"]
dataRate = "1Gbps"
delay = "0ms"

[link28]
edges = ["S7", "S8"]
dataRate = "1Gbps"
delay = "0ms"

[link29]
edges = ["S8", "S9"]
dataRate = "1Gbps"
delay = "0ms"
