[appHost1]
host = "H1"
remote = "H5"
startTime = "10s"
stopTime = "120s"
type = "constSend"
dataRate = "100Mbps"

[appHost2]
host = "H2"
remote = "H6"
startTime = "20s"
stopTime = "120s"
type = "constSend"
dataRate = "100Mbps"

[appHost3]
host = "H3"
remote = "H7"
startTime = "30s"
stopTime = "180s"
type = "constSend"
dataRate = "50Mbps"

[appHost4]
host = "H4"
remote = "H8"
startTime = "40s"
stopTime = "180s"
type = "constSend"
dataRate = "50Mbps"

[appHost5]
host = "H5"
remote = "H1"
startTime = "50s"
stopTime = "160s"
type = "constSend"
dataRate = "150Mbps"

[appHost6]
host = "H6"
remote = "H2"
startTime = "60s"
stopTime = "160s"
type = "constSend"
dataRate = "150Mbps"

[appHost7]
host = "H7"
remote = "H3"
startTime = "70s"
stopTime = "140s"
type = "constSend"
dataRate = "200Mbps"

[appHost8]
host = "H8"
remote = "H4"
startTime = "80s"
stopTime = "140s"
type = "constSend"
dataRate = "200Mbps"
