[chassis.default]
model = "cpuLoad"
percentages = [0.0, 1.0]
consumptions = [100.0, 300.0]

[chassis.weak]
model = "cpuLoad"
percentages = [0.0, 0.10, 0.25, 0.50, 0.75, 1.0]
consumptions = [10.0, 20.0, 35.0, 80.0, 150.0, 200.0]

[chassis.strong]
model = "cpuLoad"
percentages = [0.0, 0.10, 0.25, 0.50, 0.75, 1.0]
consumptions = [5.0, 15.0, 30.0, 55.0, 80.0, 120.0]