[app1]
host = "H1"
remote = "H5"
startTime = "61s"
type = "constSend"
dataRate = "100Mbps"

[app2]
host = "H1"
remote = "H6"
startTime = "121s"
type = "constSend"
dataRate = "100Mbps"

[app3]
host = "H5"
remote = "H1"
startTime = "181s"
type = "constSend"
dataRate = "100Mbps"

[app4]
host = "H6"
remote = "H1"
startTime = "241s"
type = "constSend"
dataRate = "100Mbps"

[app5]
host = "H13"
remote = "H4"
startTime = "301s"
type = "constSend"
dataRate = "100Mbps"

[app6]
host = "H14"
remote = "H9"
startTime = "361s"
type = "constSend"
dataRate = "100Mbps"

[app7]
host = "H14"
remote = "H8"
startTime = "421s"
type = "constSend"
dataRate = "100Mbps"

[app8]
host = "H9"
remote = "H10"
startTime = "481s"
type = "constSend"
dataRate = "800Mbps"

[app9]
host = "H12"
remote = "H11"
startTime = "541s"
type = "constSend"
dataRate = "800Mbps"

[app10]
host = "H11"
remote = "H4"
startTime = "601s"
type = "constSend"
dataRate = "100Mbps"

[app11]
host = "H11"
remote = "H16"
startTime = "661s"
type = "constSend"
dataRate = "100Mbps"

[app12]
host = "H11"
remote = "H8"
startTime = "721s"
type = "constSend"
dataRate = "100Mbps"

[app13]
host = "H8"
remote = "H3"
startTime = "781s"
type = "constSend"
dataRate = "100Mbps"

[app14]
host = "H15"
remote = "H16"
startTime = "841s"
type = "constSend"
dataRate = "800Mbps"