[H1]
type = "host"

[H2]
type = "host"

[H3]
type = "host"

[H4]
type = "host"

[H5]
type = "host"

[H6]
type = "host"

[H7]
type = "host"

[H8]
type = "host"

[H9]
type = "host"

[H10]
type = "host"

[H11]
type = "host"

[H12]
type = "host"

[H13]
type = "host"

[H14]
type = "host"

[H15]
type = "host"

[H16]
type = "host"

[S1]
type = "switch"
cpuCapacity = "7Gbps"

[S1.chassis]
model = "enabledPorts"
idleConso = 108
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [31.0, 52.0, 157.0]

[S1.interfaces]
model = "dataRate"
unit = "100Mbps"
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [14.0, 13.0, 11.0]

[S2]
type = "switch"
cpuCapacity = "3Gbps"

[S2.chassis]
model = "enabledPorts"
idleConso = 108
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [31.0, 52.0, 157.0]

[S2.interfaces]
model = "dataRate"
unit = "100Mbps"
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [14.0, 13.0, 11.0]

[S3]
type = "switch"
cpuCapacity = "3Gbps"

[S3.chassis]
model = "enabledPorts"
idleConso = 108
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [31.0, 52.0, 157.0]

[S3.interfaces]
model = "dataRate"
unit = "100Mbps"
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [14.0, 13.0, 11.0]

[S4]
type = "switch"
cpuCapacity = "3Gbps"

[S4.chassis]
model = "enabledPorts"
idleConso = 108
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [31.0, 52.0, 157.0]

[S4.interfaces]
model = "dataRate"
unit = "100Mbps"
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [14.0, 13.0, 11.0]

[S5]
type = "switch"
cpuCapacity = "7Gbps"

[S5.chassis]
model = "enabledPorts"
idleConso = 108
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [31.0, 52.0, 157.0]

[S5.interfaces]
model = "dataRate"
unit = "100Mbps"
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [14.0, 13.0, 11.0]

[S6]
type = "switch"
cpuCapacity = "4Gbps"

[S6.chassis]
model = "enabledPorts"
idleConso = 108
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [31.0, 52.0, 157.0]

[S6.interfaces]
model = "dataRate"
unit = "100Mbps"
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [14.0, 13.0, 11.0]

[S7]
type = "switch"
cpuCapacity = "2Gbps"

[S7.chassis]
model = "enabledPorts"
idleConso = 108
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [31.0, 52.0, 157.0]

[S7.interfaces]
model = "dataRate"
unit = "100Mbps"
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [14.0, 13.0, 11.0]

[S8]
type = "switch"
cpuCapacity = "8Gbps"

[S8.chassis]
model = "enabledPorts"
idleConso = 108
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [31.0, 52.0, 157.0]

[S8.interfaces]
model = "dataRate"
unit = "100Mbps"
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [14.0, 13.0, 11.0]

[S9]
type = "switch"
cpuCapacity = "7Gbps"

[S9.chassis]
model = "enabledPorts"
idleConso = 108
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [31.0, 52.0, 157.0]

[S9.interfaces]
model = "dataRate"
unit = "100Mbps"
dataRates = ["1Gbps", "2400Mbps", "10Gbps"]
consumptions = [14.0, 13.0, 11.0]
