[H1]
type = "host"

[H2]
type = "host"

[S1]
type = "switch"
cpuCapacity = "10Mbps"

[S1.chassis]
template = "strong"

[S2]
type = "switch"
cpuCapacity = "10Mbps"

[S2.chassis]
template = "strong"

[S3]
type = "switch"
cpuCapacity = "10Mbps"

[S3.chassis]
template = "strong"
