[H3]
type = "host"

[H4]
type = "host"

[S4]
type = "switch"
cpuCapacity = "4Mbps"

[S4.chassis]
template = "strong"

[S5]
type = "switch"
cpuCapacity = "4Mbps"

[S5.chassis]
template = "strong"

[S6]
type = "switch"
cpuCapacity = "4Mbps"

[S6.chassis]
template = "strong"
