[link1]
edges = ["H1", "S1"]
dataRate = "1Gbps"
delay = "0ms"

[link2]
edges = ["H2", "S1"]
dataRate = "1Gbps"
delay = "0ms"

[link3]
edges = ["H3", "S1"]
dataRate = "1Gbps"
delay = "0ms"

[link4]
edges = ["H4", "S1"]
dataRate = "1Gbps"
delay = "0ms"

[link5]
edges = ["S1", "S2"]
dataRate = "1Gbps"
delay = "0ms"

[link6]
edges = ["S1", "S3"]
dataRate = "1Gbps"
delay = "0ms"

[link7]
edges = ["S1", "S4"]
dataRate = "1Gbps"
delay = "0ms"

[link8]
edges = ["S2", "S6"]
dataRate = "1Gbps"
delay = "0ms"

[link9]
edges = ["S3", "S5"]
dataRate = "1Gbps"
delay = "0ms"

[link10]
edges = ["S3", "S6"]
dataRate = "1Gbps"
delay = "0ms"

[link11]
edges = ["S3", "S7"]
dataRate = "1Gbps"
delay = "0ms"

[link12]
edges = ["S4", "S8"]
dataRate = "1Gbps"
delay = "0ms"

[link13]
edges = ["S8", "S7"]
dataRate = "1Gbps"
delay = "0ms"


[link14]
edges = ["S5", "S9"]
dataRate = "1Gbps"
delay = "0ms"

[link15]
edges = ["S6", "S9"]
dataRate = "1Gbps"
delay = "0ms"

[link16]
edges = ["S7", "S9"]
dataRate = "1Gbps"
delay = "0ms"

[link17]
edges = ["S9", "H5"]
dataRate = "1Gbps"
delay = "0ms"

[link18]
edges = ["S9", "H6"]
dataRate = "1Gbps"
delay = "0ms"

[link19]
edges = ["S9", "H7"]
dataRate = "1Gbps"
delay = "0ms"

[link20]
edges = ["S9", "H8"]
dataRate = "1Gbps"
delay = "0ms"

[link21]
edges = ["S2", "S5"]
dataRate = "1Gbps"
delay = "0ms"
