[link1]
edges = ["H1", "S1"]
dataRate = "1Gbps"
delay = "0ms"

[link2]
edges = ["S1", "S2"]
dataRate = "1Gbps"
delay = "0ms"

[link3]
edges = ["S2", "S3"]
dataRate = "1Gbps"
delay = "0ms"

[link4]
edges = ["S3", "H2"]
dataRate = "1Gbps"
delay = "0ms"

[link5]
edges = ["S1", "S4"]
dataRate = "1Gbps"
delay = "0ms"

[link6]
edges = ["S4", "S5"]
dataRate = "1Gbps"
delay = "0ms"

[link7]
edges = ["S5", "S3"]
dataRate = "1Gbps"
delay = "0ms"

[link8]
edges = ["S1", "S3"]
dataRate = "1Gbps"
delay = "0ms"