[simulator]
stopTime = "1min"

[ecofen]
logFile = true
logInterval = "1s"
interval = "1s"

[switchStats]
enable = true
interval = "1s"

[linkStats]
logFile = true
logInterval = "1s"
interval = "1s"

[flowMonitor]
enable = true