[app3]
type = "sinSend"
host = "H7"
remote = "H8"
const = "1.5Mb/s"
b = 1.0
startTime = "10s"
stopTime = "190s"

[app4]
type = "sinSend"
host = "H8"
remote = "H7"
const = "1.5Mb/s"
b = 1.0
c = 2.0
startTime = "10s"
stopTime = "190s"
