[app1]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "9s"

[app2]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "19s"

[app3]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "29s"

[app4]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "39s"

[app5]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "49s"

[app6]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "59s"

[app7]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "69s"

[app8]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "79s"

[app9]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "89s"

[app10]
type = "constSend"
host = "H1"
remote = "H2"
dataRate = "20Gbps"
startTime = "99s"