[H1]
type = "host"

[H2]
type = "host"

[S1]
type = "switch"
cpuCapacity = "2400Mbps"

[S1.chassis]
template = "strong"

[S2]
type = "switch"
cpuCapacity = "2400Mbps"

[S2.chassis]
template = "strong"

[S3]
type = "switch"
cpuCapacity = "2400Mbps"

[S3.chassis]
template = "strong"

[S4]
type = "switch"
cpuCapacity = "2400Mbps"

[S4.chassis]
template = "strong"

[S5]
type = "switch"
cpuCapacity = "2400Mbps"

[S5.chassis]
template = "strong"

[S6]
type = "switch"
cpuCapacity = "2400Mbps"

[S6.chassis]
template = "strong"
